import { FileText, TrendingUp, Leaf, Trophy } from "lucide-react"

const steps = [
  {
    number: 1,
    title: "Onboard in Minutes",
    icon: FileText,
    description:
      'Engage with our AI assistant to upload your company documents. Our system instantly verifies your credentials, stakes your compliance bond, and mints your permanent "Verified Industry" NFT on the Solana blockchain. No long forms, no manual reviews, no delays.',
  },
  {
    number: 2,
    title: "Activate Your Capital",
    icon: TrendingUp,
    description:
      "Your bonded USDC doesn't just sit idle. It's automatically deposited into our Dynamic Automated Market Maker (DAMM) vault, where it begins generating real-time yield from decentralized liquidity pools. Your compliance deposit is now a productive asset.",
  },
  {
    number: 3,
    title: "Manage & Automate Compliance",
    icon: Leaf,
    description:
      "Easily report your monthly emissions on our secure portal. To stay compliant, simply burn the equivalent amount of Carbon Credit Tokens (CCTs). Our platform can even auto-purchase credits for you using the bonding curve if your emissions exceed your holdings, ensuring you never fall behind.",
  },
  {
    number: 4,
    title: "Share in the Success",
    icon: Trophy,
    description:
      "As a reward for your proactive compliance, you receive a significant share of the yield generated by the DAMM vault. We believe in aligning financial incentives with environmental responsibility to build a sustainable and profitable ecosystem for all participants.",
  },
]

export default function OnboardingSection() {
  return (
    <section className="w-full bg-white py-12 md:py-20 px-4 sm:px-8 md:px-14">
      <div className="mx-auto">
        {/* Header */}
        <div className="mb-8 sm:mb-12 md:mb-16">
          <h2 className="text-2xl sm:text-3xl md:text-5xl text-black leading-snug mb-3">
            A Simple Path <br/>to Verifiable Compliance
          </h2>
          <p className="text-base sm:text-lg md:text-xl leading-snug text-gray-600">
            We&apos;ve replaced bureaucratic hurdles with a seamless, automated, and rewarding on-chain workflow.
            Here&apos;s how your journey with CarbonOnChain unfolds in four steps.
          </p>
        </div>

        {/* Steps */}
        <div className="space-y-8 sm:space-y-10 md:space-y-12">
          {steps.map((step) => {
            const Icon = step.icon
            return (
              <div key={step.number} className="flex flex-col md:flex-row gap-4 sm:gap-6 md:gap-8">
                {/* Left - Step */}
                <div className="flex-shrink-0 w-full md:w-[30%]">
                  <div className="flex items-center gap-3 mb-3">
                    <Icon className="w-4 h-4 sm:w-5 sm:h-5 text-black" strokeWidth={1.5} />
                    <span className="text-xs sm:text-sm font-light text-gray-500">Step {step.number}</span>
                  </div>
                  <h3 className="text-base sm:text-lg md:text-xl font-light text-black leading-tight">{step.title}</h3>
                </div>

                {/* Right - Content */}
                <div className="flex-1 pt-0 md:pt-1">
                  <p className="text-xs sm:text-sm md:text-base font-light text-gray-700 leading-relaxed">
                    {step.description}
                  </p>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </section>
  )
}
